source 'https://rubygems.org'

gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'
gem 'puma', '~> 6.0'
gem 'rackup', '~> 2.2'
gem 'dotenv', '~> 3.0'
gem 'json', '~> 2.7'

# Local tapsilat gem
gem 'tapsilat', path: '../../sdks/tapsilat-ruby'
